version: '3'
 
services:
  omeka_apache:
    container_name: omeka_apache_con
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    volumes:
      - ./logs/apache:${APACHE_ROOT_DIR}/logs
      - ./htdocs:${APACHE_ROOT_DIR}/htdocs
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
      - PHP_IP=${PHP_IP}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
  omeka_maria:
    container_name: omeka_maria_con
    build:
      context: ./maria
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    volumes:
      - ../logs/mysql:${MYSQL_LOG_DIR}
      - ../database:${MYSQL_DATA_DIR}
    networks:
      public_net:
        ipv4_address: ${MYSQL_IP}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
  omeka_php:
    container_name: omeka_php_con
    build:
      context: ./php
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    working_dir: ${PHP_APP_DIR}
    volumes:
      - ./htdocs:${PHP_APP_DIR}
      - ./logs/php:${PHP_ROOT_DIR}/logs
    depends_on:
      - omeka_apache
      - omeka_maria
    links:
      - omeka_maria
    networks:
      public_net:
        ipv4_address: ${PHP_IP}
    user: ${WEB_USER}

    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
 
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}